package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/gophersnacks/gsweb/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Course)
// DB Table: Plural (courses)
// Resource: Plural (Courses)
// Path: Plural (/courses)
// View Template Folder: Plural (/templates/courses/)

// CoursesResource is the resource for the Course model
type CoursesResource struct {
	buffalo.Resource
}

// List gets all Courses. This function is mapped to the path
// GET /courses
func (v CoursesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	courses := &models.Courses{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Courses from the DB
	if err := q.All(courses); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, courses))
}

// Show gets the data for one Course. This function is mapped to
// the path GET /courses/{course_id}
func (v CoursesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Course
	course := &models.Course{}

	// To find the Course the parameter course_id is used.
	if err := tx.Find(course, c.Param("course_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, course))
}

// New renders the form for creating a new Course.
// This function is mapped to the path GET /courses/new
func (v CoursesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Course{}))
}

// Create adds a Course to the DB. This function is mapped to the
// path POST /courses
func (v CoursesResource) Create(c buffalo.Context) error {
	// Allocate an empty Course
	course := &models.Course{}

	// Bind course to the html form elements
	if err := c.Bind(course); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(course)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, course))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Course was created successfully")

	// and redirect to the courses index page
	return c.Render(201, r.Auto(c, course))
}

// Edit renders a edit form for a Course. This function is
// mapped to the path GET /courses/{course_id}/edit
func (v CoursesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Course
	course := &models.Course{}

	if err := tx.Find(course, c.Param("course_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, course))
}

// Update changes a Course in the DB. This function is mapped to
// the path PUT /courses/{course_id}
func (v CoursesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Course
	course := &models.Course{}

	if err := tx.Find(course, c.Param("course_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Course to the html form elements
	if err := c.Bind(course); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(course)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, course))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Course was updated successfully")

	// and redirect to the courses index page
	return c.Render(200, r.Auto(c, course))
}

// Destroy deletes a Course from the DB. This function is mapped
// to the path DELETE /courses/{course_id}
func (v CoursesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Course
	course := &models.Course{}

	// To find the Course the parameter course_id is used.
	if err := tx.Find(course, c.Param("course_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(course); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Course was destroyed successfully")

	// Redirect to the courses index page
	return c.Render(200, r.Auto(c, course))
}
